### ISSUE TITLE
01. Responsive website [8]

### ISSUE THREAD

**Issue by franpossetto** [franpossetto/nina-bim-web#1]
Convert the site to responsive, for:
1. Web
2. Tablet (horizontal and vertical).
3. Mobile (horizontal and vertical).

Design checklist:
- [ ] Web (as it is now).
- [ ] Tablet Horizontal: similar to website.
- [ ] Tablet Vertical: Using the same elements, and following this order vertically [ 1. Logo 2. Title, 3. Button (download),  4. GitHub ]
- [ ] Phone vertical: Using the same elements, and following this order vertically [ 1. Logo 2. Title, 3. Button (share),  4. GitHub ]
- [ ] Phone horizontal: IDK yet.

**Comment by franpossetto** [comment]
Bulma.io 
https://bulma.io/

**Comment by manuelserafin** [comment]
320px y 425px mobile
426px y 768px tablet
769px o mas desktop

**Comment by manuelserafin** [comment]
@franpossetto, please check if the responsive is working on your monitor type? I tested on FHD and HD resolution with ok results.

**Comment by manuelserafin** [comment]
Next step is to work on the responsive of the tablet so that it interprets landscape and portrait.
